### ISSUE TITLE
Re: Dynamically adding to the classpath in a post Java 9 world. Help?

### ISSUE THREAD

**Issue by mikub** [plexus/classpath_test#1]
Hi Arne,
came across your (now closed) question on clojureverse.
I actually struggled with the same issue and ultimately managed to make it work. See for example [here](https://github.com/mikub/titanoboa/blob/713910eec1534f7c6cce3fa9bc5bfd6a99d2a062/src/clj/titanoboa/server.clj#L127) .
Took me quite a long time before realizing that things that do not work in REPL might work in standalone mode (I was kinda expecting it to be only the other way around). So basically though my solution does not work in REPL (probably due to new classloaders being created and bound repeatedly), when run normally (via java -jar ...) it actually works! 

Cheers
Miro

**Comment by plexus** [comment]
Hi @mikub, I've [reopened the topic](https://clojureverse.org/t/dynamically-adding-to-the-classpath-in-a-post-java-9-world-help/2520/6), would you mind posting your response and continuing the conversation there?
